add lives and level to viewer and explosion bug fixed
dgomes/iia-ia-bomberman pull request #6
Opened 2019-10-22 15:05 UTC by FilipeMiguelVale

2019-10-22 15:50 UTC, dgomes requested changes

2019-10-22 15:50 UTC, dgomes commented on viewer.py
> +                                                                # do this command in your project directory convert data/nes.png data/nes.png
ja converteste a imagem... tira lá estes comentários

2019-10-22 15:50 UTC, dgomes commented on viewer.py
> +
remove

2019-10-22 15:50 UTC, dgomes commented on viewer.py
> +        SCREEN.blit(BACKGROUND, (0, 0))
pintar tudo não... remove

2019-10-22 15:50 UTC, dgomes commented on viewer.py
> +            draw_info(SCREEN, text, (650, 0))
explica la o 650...

2019-10-24 13:54 UTC, dgomes requested changes

2019-10-24 13:54 UTC, dgomes commented on viewer.py
> +    SPRITES = pygame.image.load("data/nes.png").convert_alpha()
tira o espaço do funda da linha

2019-10-24 13:54 UTC, dgomes commented on viewer.py
> +            draw_info(SCREEN, text.zfill(6), (5, 1))
explica...

2019-10-24 13:54 UTC, dgomes commented on viewer.py
> +            draw_info(SCREEN, text, (4000, 1))
q faz isto ?

2019-10-26 21:43 UTC, dgomes commented on viewer.py
> +            draw_info(SCREEN, text.zfill(6), (5, 1))
dar margem certo ? não vai demasiado para cima do mapa ?

2019-10-26 21:43 UTC, dgomes commented on viewer.py
> +            draw_info(SCREEN, text, (4000, 1))
1 pixel apenas :) ?

2019-10-26 21:58 UTC, FilipeMiguelVale commented on viewer.py
> +            draw_info(SCREEN, text, (4000, 1))
Sim, chega para não ficar colado o texto aos limites da janela :)

2019-10-26 23:21 UTC, dgomes approved these changes

2019-10-26 23:25 UTC, merged